### ISSUE TITLE
How to customize color of the dot?

### ISSUE THREAD

**Issue by mocheng** [supercrabtree/hyperterm-dibdabs#2]
Perhaps the README can be updated with instructions.

**Comment by billh93** [comment]
I second that. +1

**Comment by supercrabtree** [comment]
Sorry, I missed this. To be honest I don't really use HyperTerm (even though I think it has great potential) I just wrote this as a quick mess about. If you want to customise the color of the dot you would need to the edit the code here:

https://github.com/supercrabtree/hyperterm-dibdabs/blob/master/index.js#L7

I am just deferring to my hashbow lib here, but you could easily edit and make special conditions if you wanted. i.e.

``` js
exports.getTabProps = function (uid, parentProps, props) {
  let dabColor;
  if (props.text === '~') dabColor = '#FF0000';
  return Object.assign({}, props, {
    dabColor: dabColor || hashbow(props.text)
  });
};
```

Is this what you mean?

**Comment by danieldelcore** [comment]
Just to let you know, i've raised a PR to address this issue: https://github.com/supercrabtree/hyperterm-dibdabs/pull/4

Thanks for sharing @mocheng and @billh93
